.build/obj_lily58_rev1_PiXeL16/quantum/nvm/eeprom/nvm_dynamic_keymap.o: \
 quantum/nvm/eeprom/nvm_dynamic_keymap.c keyboards/lily58/config.h \
 .build/obj_lily58_rev1_PiXeL16/src/info_config.h \
 keyboards/lily58/keymaps/PiXeL16/config.h \
 quantum/split_common/post_config.h quantum/compiler_support.h \
 quantum/keycodes.h platforms/eeprom.h quantum/dynamic_keymap.h \
 quantum/nvm/nvm_dynamic_keymap.h \
 quantum/nvm/eeprom/nvm_eeprom_eeconfig_internal.h quantum/eeconfig.h \
 quantum/action_layer.h quantum/keyboard.h platforms/timer.h \
 platforms/avr/_timer.h quantum/action.h platforms/progmem.h \
 quantum/keycode.h quantum/modifiers.h quantum/action_code.h \
 quantum/bitwise.h quantum/util.h quantum/bits.h platforms/avr/_util.h \
 quantum/nvm/eeprom/nvm_eeprom_via_internal.h quantum/via.h

keyboards/lily58/config.h:

.build/obj_lily58_rev1_PiXeL16/src/info_config.h:

keyboards/lily58/keymaps/PiXeL16/config.h:

quantum/split_common/post_config.h:

quantum/compiler_support.h:

quantum/keycodes.h:

platforms/eeprom.h:

quantum/dynamic_keymap.h:

quantum/nvm/nvm_dynamic_keymap.h:

quantum/nvm/eeprom/nvm_eeprom_eeconfig_internal.h:

quantum/eeconfig.h:

quantum/action_layer.h:

quantum/keyboard.h:

platforms/timer.h:

platforms/avr/_timer.h:

quantum/action.h:

platforms/progmem.h:

quantum/keycode.h:

quantum/modifiers.h:

quantum/action_code.h:

quantum/bitwise.h:

quantum/util.h:

quantum/bits.h:

platforms/avr/_util.h:

quantum/nvm/eeprom/nvm_eeprom_via_internal.h:

quantum/via.h:
